### ISSUE TITLE
Cannot handle some OP_RETURN

### ISSUE THREAD

**Issue by lekanovic** [richardkiss/pycoin#146]
Hi,
I am using the insight.py to get transactions and all works fine. However I just noticed that when I use insight.py:get_tx function it fails for some OP_RETURN transactions.
Here is an example of such a transaction:
https://gist.github.com/lekanovic/4eb32667a5a7ddbfbe35

After some debugging I found that this was causing the problem:
In insight.py:tx_from_json_dict
When the argument was "OP_RETURN 3043941" to the tools.compile function then it would will a raise an exception.
tools.compile(vin.get("scriptSig").get("asm"))

I am not sure it the OP_RETURN transaction is incorrect but for me it looks okej. Just a notice it does not fail OP_RETURN that has 40bytes of data just the on that is less than 40bytes.

**Comment by XertroV** [comment]
The output in question has a malformed `asm` value that does not correspond to the `hex` value:

```
        {
            "value": "0.00000000",
            "n": 2,
            "scriptPubKey": {
                "asm": "OP_RETURN 3043941",
                "hex": "6a0365722e",
                "type": "nulldata"
            }
        },
```

This output is inconsistent with other outputs in the [gist](https://gist.github.com/lekanovic/4eb32667a5a7ddbfbe35):

```
                "asm": "OP_RETURN 436875636b204e6f7272697320646f65736e277420736179202671756f743b77686f277320796f75",
                "hex": "6a28436875636b204e6f7272697320646f65736e277420736179202671756f743b77686f277320796f75",
```

You can see that after the OP_RETURN and length byte the hex matches. And again:

```
"asm": "OP_RETURN 722064616464792671756f743b2c2062656361757365206865206b6e6f77732074686520616e7377",
                "hex": "6a28722064616464792671756f743b2c2062656361757365206865206b6e6f77732074686520616e7377",
```
    
@lekanovic can you provide any more details about how or where the JSON is being produced?

**Comment by lekanovic** [comment]
Thanks for the very quick answer! So when using insight.py to read a transaction id i got a exception. When I tried the exact same transaction id in insight it produced the json from my gist. Yes maybe this is a bug in insight

**Comment by lekanovic** [comment]
Well I can confirm that its not Insight-api that generates the incorrect asm. I am using ScriptNulldata.py with a short string as input.

Example to trigger the error:
from pycoin.tx.script import tools

op = "OP_RETURN %s" % b2h('hej')
op = tools.compile(op)

print tools.compile(op)

>  File "temp.py", line 137, in <module>
    print tools.compile(op)
  File "/home/navodar/project/bitcoin/ENV/local/lib/python2.7/site-packages/pycoin/tx/script/tools.py", line 102, in compile
    t = binascii.unhexlify(t.encode("utf8"))
TypeError: Odd-length string

**Comment by lekanovic** [comment]
Found the problem!
Seems that if you add a string to ScriptNulldata that is shorter than 5 char then this will trigger the corrupted transaction script.

Example:
   short_msg = 'AAA'
   script = ScriptNulldata(short_msg).script()
   out = TxOut(5, script)

If you add this TxOut to a transaction it will trigger the corrupt OP_RETURN script in the transaction.

Like this
   "asm": "OP_RETURN 779182450",
   "hex": "6a047261712e",

**Comment by richardkiss** [comment]
It sounds like you're saying that this is an Insight bug, right? I'd like to close this.

**Comment by lekanovic** [comment]
Sorry for my late answer,

What I meant was that if you are sending a string that is less than 5 characters to the ScriptNulldata class it will give you a corrupt script that looks like this:

"asm": "OP_RETURN 779182450",
"hex": "6a047261712e",

To reproduce this bug:

short_msg = 'AAA'
script = ScriptNulldata(short_msg).script()
out = TxOut(5, script)

If you use this output in a transaction it will be corrupt, asm and hex will look like the example above.

**Comment by richardkiss** [comment]
Do you have an example that's in the blockchain that I can look at?

**Comment by XertroV** [comment]
I don't think this is a bug in the ScriptNulldata. I've written some extra tests with short strings, and although the zero-length nulldata isn't handled it looks like 1 and 2 character scripts are okay. (There are no zero-length nulldatas on the blockchain (script: `6a00`), or at least bitcoind doesn't recognise them if there are - whether this should be handled or not is debatable)

@richardkiss There is a tx on the blockchain with a 1 byte OP_RETURN and using `services.blockr_io.get_tx()` it seems to work okay and looks like the pycoin tx object is correct: https://blockchain.info/tx/da7b34266ba43add9f7507f51f30db91a89d742a639dc542dde02f4be4cc9c91

The reason @lekanovic has the in his first example error is because op is redefined:

```
from pycoin.tx.script import tools
op = "OP_RETURN %s" % b2h('hej')
op = tools.compile(op)
print tools.compile(op)  # this 'compiles' it twice, equiv to print(tools.compile(tools.compile(op))
```

Some of the `asm` fields contain odd-length strings which will fail if compiled because they're mean to be hex.

Also, I can't replicate the following:

```
short_msg = 'AAA'
script = ScriptNulldata(short_msg).script()
out = TxOut(5, script)
```

I have included this in the test-cases and will produce a PR soon.

@lekanovic the issue still looks like a json-encoding issue. How are you converting the tx to json? If you are creating a raw transaction, printing the hex, and decoding in insight this is still probably an insight bug.

**Comment by lekanovic** [comment]
@XertroV, Great that you have a test case covering this. We can close this issue as it seems to be a insight problem and not Pycoin.
