### ISSUE TITLE
BIP32 warning

### ISSUE THREAD

**Issue by rca** [richardkiss/pycoin#255]
The README contains the warning below.  Is the warning basically saying something along the lines of, “A BIP32 wallet contains a master private key and a master public key.  DO NOT PUBLISH EITHER ONE PUBLICLY.  Use the master public key to generate publishable public keys.”

Am I understanding the warning correctly?  As I understand it, BIP32 has the advantage of generating public keys without having access to the private key in addition to not being able to trace all public keys back to a single wallet.  I do not understand whether the warning suggests that ANY PUBLIC KEY can traverse up and down the tree to discover the wallet.

I will happily update the readme once I understand what it’s warning about. 

Thanks!

>WARNING: be extremely careful giving out public wallet keys. If someone has access to a private wallet key P, of course they have access to all descendent wallet keys of P. But if they also have access to a public wallet key K where P is a subkey of K, you can actually work your way up the tree to determine the private key that corresponds to the public wallet key K (unless private derivation was used at some point between the two keys)! Be sure you understand this warning before giving out public wallet keys!

**Comment by richardkiss** [comment]
Not publishing either publicly will eliminate risk for sure.

If you have a bip32 key K and you give out the xpub for K, and also give out the PRIVATE key for K/0/0/1/2/5, it's possible to traverse up backwards through the 5, 2, 1, 0, 0 to get the xprv for K.

If you give out K/0/0'/1/2/5, you're okay because it gets stuck at the 0' level (although all the keys under K/0/0' are compromised).

See also https://github.com/richardkiss/pycoin/blob/develop/pycoin/crack/bip32.py which will recover these keys. Try it out!
