### ISSUE TITLE
Move BIP32 parsing to BIP32Node

### ISSUE THREAD

**Issue by kousu** [richardkiss/pycoin#321]
I would like to be able to say

```
from pycoin.key import BIP32Node
key = BIP32Node.from_base58("xprv9s21ZrQH143K3QTDL4LXw2F7HEK3wJUD2nW2nRk4stbPy6cq3jPPqjiChkVvvNKmPGJxWUtg6LnF5kejMRNNU3TGtRBeJgk33yuGBxrMPHi") # don't worry, this is the bip32 test key
```

Currently I need to do

```
import pycoin.symbols.btc import network
key = pycoin.symbols.btc.network.ui.parse("xprv9s21ZrQH143K3QTDL4LXw2F7HEK3wJUD2nW2nRk4stbPy6cq3jPPqjiChkVvvNKmPGJxWUtg6LnF5kejMRNNU3TGtRBeJgk33yuGBxrMPHi")
```

Which pulls in a bunch of stuff I don't care about just to do a simple thing.

I would like to submit a patch, when I have time, which addresses this.

The BIP32 parsing is currently split somehow between all these files

https://github.com/richardkiss/pycoin/blob/994c4c714f599c795f4b7d7f305926ca6cdd0349/pycoin/encoding/b58.py#L39-L48

 https://github.com/richardkiss/pycoin/blob/994c4c714f599c795f4b7d7f305926ca6cdd0349/pycoin/ui/Parser.py#L94-L101

https://github.com/richardkiss/pycoin/blob/994c4c714f599c795f4b7d7f305926ca6cdd0349/pycoin/ui/BIP32Parser.py#L9-L16

I would like to move it all (except maybe b58.py) into. I realize this is complicated by the xpub/xpriv prefix trick that is _variable_ across coins (argh), and by the need for the BIP32Nodes to always operate over `secp256k1_generator`.

(it's not 100% clear to me if the [spec](https://github.com/bitcoin/bips/blob/master/bip-0032.mediawiki#specification-key-derivation) insists on secp256k1 or only suggests it; that would change how this has to be written)

**Comment by richardkiss** [comment]
Since you filed this, I've since moved all parsing (see the feature/parser branch https://github.com/richardkiss/pycoin/tree/feature/parser), and expect I will move it again in a future refactoring. It's not under `network.parse_bip32_prv` and `network.parse_bip32_pub`. However, it does seem necessary to keep it scoped under a specific network since each network defines its own `xprv`-type prefix.

To me, it seems bad to teach BIP32Node.py about all possible networks, since that would mean adding a new network would involved editing BIP32Node.py. What do you think?
