### ISSUE TITLE
Fixed in one of PRs #100 xor #98 - BIP32 subkey derivation raises exception for negative indexes (contrary to documentation)

### ISSUE THREAD

**Issue by posita** [richardkiss/pycoin#97]
*UPDATE: the functionality supporting negative integers as hardened subkeys is added in PR #98 and removed altogether in PR #100. Those PRs are mutually exclusive and only one should be merged. My personal recommendation is to merge #100 and close (reject) #98 for the reasons outlined in https://github.com/richardkiss/pycoin/issues/97#issuecomment-81428271 below.*

---

Unless I've misinterpreted, according to [the docs](https://github.com/richardkiss/pycoin/blob/5a3f30986dec6b4e82c45c0955c139891ce8ba0f/pycoin/key/BIP32Node.py#L183), the following should be equivalent:

```python
i = 23
bip32_node.subkey(i, is_hardened=True)
bip32_node.subkey(-i)
```

However, see [this line](https://github.com/richardkiss/pycoin/blob/5a3f30986dec6b4e82c45c0955c139891ce8ba0f/pycoin/key/BIP32Node.py#L188) (reproduced with some context below). In short, note the `raise ValueError(...)` statement prevents submitting a negative index, and also prevents execution of the rest of the `if` statement:

```python
...
    def _subkey(self, i, is_hardened, as_private):
        """Yield a child node for this node.
        i: the index for this node.
        is_hardened: use "hardened key derivation". That is, the public version
        of this node cannot calculate this child.
        as_private: set to True to get a private subkey.
        Note that setting i<0 uses private key derivation, no matter the
        value for is_hardened."""
        ...
        if i < 0:
            raise ValueError("i can't be negative")  # <-- BRAIN DAMAGE(?)
            is_hardened = True
            i = -i
            i |= 0x80000000
        ...
...
```

**Comment by mbogosian** [comment]
I was dimly aware of this when I [wrote the test](https://github.com/mbogosian/pycoin/blob/28fa435f15fd496976cb99eaca90444c16d1cf44/tests/bip32_test.py#L157) along with my fix for #97 (PR #98), but I didn't realize the implications until daydreaming about it just now.<sup>1</sup>

Allowing negative numbers to represented hardened children with in a `BIP32Node` may be confusing, since there's no way to represent a hardened subkey at index 0. In python:

```python
>>> -0 == 0
True
>>> -0 < 0
False
```

This means that [`BIP32Node.subkey(i=-0)` will always yield the ***un***hardened subkey](https://github.com/mbogosian/pycoin/blob/28fa435f15fd496976cb99eaca90444c16d1cf44/pycoin/key/BIP32Node.py#L190) (just like `BIP32Node.subkey(i=0)`). Given this oddity (and that 0 is probably a very popular index), it's probably best not to support using negative numbers for hardened subkeys at all, and instead rely on explicit parameters or the `H` notation in [`BIP32Node.subkey_for_path`](https://github.com/mbogosian/pycoin/blob/28fa435f15fd496976cb99eaca90444c16d1cf44/pycoin/key/BIP32Node.py#L230).

<sup>1</sup> The fact that the test wouldn't pass for `i = 0` should have tipped me off, but hey, better late than never, right? :grin:
